#!/bin/bash
set -o errexit
assert_no_failures=true
expect_success() {
    ( "$@"; ) || {
        local actual_exit_code="$?"
        echo "Failed expectation for command: \`$*'"
        echo " - expected success (exit code == 0) got failure (exit code == $actual_exit_code)"
        assert_no_failures=false
    }
}

expect_output() {
    local expected_output="$1"; shift
    local command="$*"
    local actual_output="$( "$@"; )"
    [[ "$actual_output" == "$expected_output" ]] || {
        echo "Failed expectation for command: \`$command'"
        echo " - expected output: $expected_output"
        echo " -   actual output: $actual_output"
    }
}

expect_success true
expect_output 'foo
bar' \
    echo 'foo
bar'

$assert_no_failures
